const movieData = {
        'fantastic-four': {
            title: 'The Fantastic Four: First Steps',
            description: 'A superhero family with cosmic powers faces personal struggles and galactic threats.',
            image: '/assets/movies/fantastic-four.jpeg',
            director: 'Matt Shakman',
            writers: 'Josh Friedman, Eric Pearson, Jeff Kaplan',
            stars: 'Pedro Pascal, Vanessa Kirby, Ebon Moss-Bachrach',
            tags: ['Action', 'Adventure', 'Sci-Fi', 'Superhero'],
            rating: '7.4',
            reviews: '77.5K',
            content: 'Set against the vibrant backdrop of a *1960s-inspired world*, *Fantastic Four: First Steps* reimagines the origin story of Marvel\'s first family.\n\nWhen a space mission goes awry, four astronauts gain *incredible cosmic powers* that forever change their lives.\n\nReed Richards becomes *Mr. Fantastic* with the ability to stretch his body, while Sue Storm gains *invisibility and force fields* as the Invisible Woman. Johnny Storm transforms into the *Human Torch* with pyrokinetic abilities, and Ben Grimm becomes the *Thing* with superhuman strength.\n\nAs they struggle to control their new abilities and maintain their relationships, the team must unite to face *Doctor Doom*, a brilliant but megalomaniacal scientist whose own experiments have given him incredible power.\n\nThe film explores themes of *family*, *responsibility*, and the *cost of heroism* while delivering spectacular action sequences and emotional depth.\n\nDirector *Matt Shakman* brings a fresh perspective to the beloved characters, balancing *humor and heart* with *cosmic-scale adventure*. The film promises to launch a new era for the Fantastic Four in the Marvel Cinematic Universe.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'guardians-galaxy-vol2': {
            title: 'Guardians of the Galaxy Vol. 2',
            description: 'The Guardians struggle to keep together as a team while dealing with Peter Quill\'s parentage.',
            image: '/assets/movies/gog.jpg',
            director: 'James Gunn',
            writers: 'James Gunn',
            stars: 'Chris Pratt, Zoe Saldana, Dave Bautista',
            tags: ['Action', 'Adventure', 'Comedy', 'Sci‑Fi'],
            rating: '7.6',
            reviews: '634K',
            content: 'Set shortly after the original *Guardians* film, the team is hired by the *Sovereign* to protect valuable battery cells. When Rocket steals them, the Sovereign attacks.\n\nThe Guardians crash‑land on a remote planet, where Peter meets his father *Ego*, a god‑like Celestial who reveals Peter’s heritage. As the truth of Ego’s destructive plans emerges, the Guardians unite to *destroy Ego’s brain* at the planet’s core.\n\n*Yondu sacrifices himself* to save Peter, and Nebula departs on her own path. In a post‑credits scene, *Adam Warlock* is teased. Groot also appears in his *teenage* form.\n\nThemes include *family*, *identity*, and *redemption*.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'atlas': {
            title: 'Atlas',
            description: 'A brilliant counterterrorism analyst fights an AI soldier in a war against artificial intelligence.',
            image: '/assets/movies/atl.jpeg',
            driver: 'Brad Peyton',
            writers: 'Leo Sardarian, Aron Eli Coleite',
            stars: 'Jennifer Lopez, Simu Liu, Sterling K. Brown',
            tags: ['Action', 'Sci‑Fi', 'Thriller'],
            rating: '5.7',
            reviews: '45K',
            content: 'In the year *2043*, evil AI terrorist *Harlan* (Simu Liu) leads a mass genocide and flees Earth. By *2071*, analyst *Atlas Shepherd* (Jennifer Lopez) is called into action.\n\nStranded on a hostile planet, Atlas is forced to *neural-link* with an AI named *Smith* to survive. Though she distrusts AI, she must learn to trust Smith as they work together to prevent *global annihilation*.\n\nSmith sacrifices himself, but a final scene hints at his *possible revival*. The film explores *trust*, *humanity*, and *tech dependency*, though reception was mixed due to heavy CGI and weak narrative depth.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'pacific-rim': {
            title: 'Pacific Rim',
            description: 'Humans pilot giant robots to fight monstrous creatures emerging from the ocean.',
            image: '/assets/movies/pcr.jpg',
            director: 'Guillermo del Toro',
            writers: 'Travis Beacham, Guillermo del Toro',
            stars: 'Charlie Hunnam, Idris Elba, Rinko Kikuchi',
            tags: ['Action', 'Adventure', 'Sci‑Fi'],
            rating: '6.9',
            reviews: '523K',
            content: 'In the near future, monstrous *Kaiju* emerge from a portal beneath the Pacific Ocean. To counter them, humans create giant mechs called *Jaegers*, which require *two pilots* connected via neural link known as the *Drift*.\n\nPilot *Raleigh Becket* returns to duty alongside *Mako Mori* to operate *Gipsy Danger*. As attacks escalate, the team launches a daring nuclear strike into the portal to end the invasion.\n\n*Pentecost* and the co-pilots make the ultimate sacrifice. The film delivers *spectacle*, *teamwork*, and *global unity* through breathtaking battles.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'spiderman-no-way-home': {
            title: 'Spider-Man: No Way Home',
            description: 'Spider-Man\'s identity is revealed and he seeks help from Doctor Strange.',
            image: '/assets/movies/spd.jpeg',
            director: 'Jon Watts',
            writers: 'Chris McKenna, Erik Sommers',
            stars: 'Tom Holland, Zendaya, Benedict Cumberbatch',
            tags: ['Action', 'Adventure', 'Sci‑Fi'],
            rating: '8.2',
            reviews: '765K',
            content: 'After *Mysterio* reveals Peter Parker’s identity, Peter’s life spirals. Facing rejection from colleges and public backlash, he turns to *Doctor Strange* for help.\n\nThe botched spell opens the *multiverse*, bringing villains from other realities: *Doc Ock*, *Green Goblin*, *Electro*, *Lizard*, and *Sandman*. With the arrival of alternate Spider-Men (*Tobey Maguire* and *Andrew Garfield*), the trio works together to *cure the villains*.\n\nIn a heart-wrenching decision, Peter asks Strange to make *everyone forget him*. He chooses anonymity to protect his loved ones, embracing his role as Spider-Man anew, *alone but resolute*.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            fileId: '6890623d0037763406d4',
        },
        'dune-part-two': {
            title: 'Dune: Part Two',
            description: 'Paul Atreides unites with Chani and the Fremen to seek revenge on the conspirators who destroyed his family.',
            image: '/assets/movies/dune-part-two.jpg', // Anda perlu menambahkan file gambar ini
            director: 'Denis Villeneuve',
            writers: 'Denis Villeneuve, Jon Spaihts',
            stars: 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
            tags: ['Action', 'Adventure', 'Sci-Fi', 'Drama'],
            rating: '8.6',
            reviews: '481K',
            content: 'Paul Atreides continues his journey on the desert planet of *Arrakis*. Now united with *Chani and the Fremen*, he seeks revenge against *House Harkonnen* and the conspirators who destroyed his family.\n\nAs he masters the ways of the desert and grapples with his prophetic visions, Paul must choose between the love of his life and the fate of the universe. He endeavors to prevent a terrible future only he can foresee, leading his warriors into a holy war against the Padishah Emperor.\n\nThe film explores themes of *power*, *destiny*, *religion*, and the *consequences of colonialism* on a galactic scale, delivering breathtaking visuals and epic battles.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'interstellar': {
            title: 'Interstellar',
            description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
            image: '/assets/movies/interstellar.jpg', // Anda perlu menambahkan file gambar ini
            director: 'Christopher Nolan',
            writers: 'Jonathan Nolan, Christopher Nolan',
            stars: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
            tags: ['Adventure', 'Drama', 'Sci-Fi'],
            rating: '8.7',
            reviews: '2.1M',
            content: 'In Earth\'s future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. A former NASA pilot, *Cooper*, is tasked with a critical mission: to pilot a spacecraft through a *wormhole near Saturn* in search of a new habitable planet.\n\nCooper and his team travel to distant galaxies, encountering planets where *time dilation* has extreme effects—hours on one planet equal decades on Earth. They face betrayal, loss, and the immense loneliness of space.\n\nUltimately, the journey becomes a race against time to save humanity, testing the bonds of *love, loss, and sacrifice* across dimensions. The film is a visual masterpiece exploring complex scientific theories and profound human emotions.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },

        'blade-runner-2049': {
            title: 'Blade Runner 2049',
            description: 'A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.',
            image: '/assets/movies/blade-runner-2049.jpg', // Anda perlu menambahkan file gambar ini
            director: 'Denis Villeneuve',
            writers: 'Hampton Fancher, Michael Green',
            stars: 'Ryan Gosling, Harrison Ford, Ana de Armas',
            tags: ['Action', 'Drama', 'Mystery', 'Sci-Fi'],
            rating: '8.0',
            reviews: '652K',
            content: 'In 2049, bioengineered humans known as *replicants* are slaves. K, a Nexus-9 replicant, works for the LAPD as a *"blade runner"*, an officer who hunts down and retires rogue replicants.\n\nDuring an investigation, K uncovers a long-buried secret: the remains of a replicant who died during childbirth. This discovery threatens to *shatter the fragile stability* between humans and replicants. K\'s orders are to find and eliminate the child to prevent a potential war.\n\nHis quest leads him on a search for *Rick Deckard*, a former blade runner who has been missing for 30 years. The film delves into themes of *identity, memory, and what it truly means to be human* in a visually stunning, neo-noir landscape.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },
        'arrival': {
            title: 'Arrival',
            description: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
            image: '/assets/movies/arrival.jpg',
            director: 'Denis Villeneuve',
            writers: 'Eric Heisserer, Ted Chiang',
            stars: 'Amy Adams, Jeremy Renner, Forest Whitaker',
            tags: ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
            rating: '7.9',
            reviews: '745K',
            content: 'When twelve enigmatic alien spacecraft land at different locations across the globe, the world is thrown into turmoil. To prevent a potential global war, the U.S. military recruits elite linguist *Dr. Louise Banks* (Amy Adams) to lead a team to establish communication with the extraterrestrial visitors.\n\nAs Louise begins to decipher their complex, non-linear language, she experiences vivid flashbacks that reveal a profound personal connection to the aliens\' purpose. The language of the "Heptapods" fundamentally alters her perception of *time*, blurring the lines between past, present, and future.\n\nShe must race against time to interpret their message before other nations, driven by fear and suspicion, launch an attack. The film is a thought-provoking exploration of *communication*, *time*, and *humanity\'s response to the unknown*, culminating in a deeply emotional and mind-bending revelation.',
            redirectUrl: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
            redirectUrl2: 'https://dwightcherrykings.com/sa275vh7?key=ad56867b7c2622a482d3367dcd098b66',
        },
};